export const MOCK_ACTIVITIES = [
  // ── Musées ──────────────────────────────────────────────────────
  { id: 'mock-m1', name: 'Musée du Louvre', category: 'museum',
    address: 'Rue de Rivoli, 75001 Paris', distance: '1.2 km',
    description: 'Le plus grand musée du monde : la Joconde, la Vénus de Milo, des millénaires d\'histoire.',
    openingHours: 'Lun-Dim 9h-18h (fermé mar)', website: 'https://www.louvre.fr',
    rating: 4.7, lat: 48.8606, lng: 2.3376 },
  { id: 'mock-m2', name: 'Centre Pompidou', category: 'museum',
    address: 'Place Georges-Pompidou, 75004 Paris', distance: '0.8 km',
    description: 'Art moderne et contemporain dans un bâtiment avant-gardiste de Renzo Piano.',
    openingHours: 'Mer-Lun 11h-21h', website: 'https://www.centrepompidou.fr',
    rating: 4.5, lat: 48.8607, lng: 2.3527 },
  { id: 'mock-m3', name: "Musée d'Orsay", category: 'museum',
    address: "1 Rue de la Légion d'Honneur, 75007", distance: '2.1 km',
    description: 'Collection impressionniste et post-impressionniste dans une somptueuse ancienne gare.',
    openingHours: 'Mar-Dim 9h30-18h', website: 'https://www.musee-orsay.fr',
    rating: 4.8, lat: 48.8600, lng: 2.3265 },
  { id: 'mock-m4', name: 'Palais de Tokyo', category: 'museum',
    address: '13 Ave du Président Wilson, 75116', distance: '3.5 km',
    description: 'Site de création contemporaine avec expositions immersives et événements nocturnes.',
    openingHours: 'Lun-Dim 12h-0h (fermé mar)',
    rating: 4.3, lat: 48.8634, lng: 2.2974 },
  { id: 'mock-m5', name: 'Musée Rodin', category: 'museum',
    address: '77 Rue de Varenne, 75007 Paris', distance: '2.8 km',
    description: 'Le Penseur, le Baiser… les chefs-d\'œuvre de Rodin dans un hôtel particulier et son jardin.',
    openingHours: 'Mar-Dim 10h-18h30', website: 'https://www.musee-rodin.fr',
    rating: 4.6, lat: 48.8555, lng: 2.3157 },

  // ── Restaurants ──────────────────────────────────────────────────
  { id: 'mock-r1', name: 'Le Comptoir du Relais', category: 'restaurant',
    address: "9 Carrefour de l'Odéon, 75006", distance: '1.8 km',
    description: 'Bistrot parisien emblématique : cuisine bistronomique de Yves Camdeborde, terrasse animée.',
    openingHours: 'Mar-Dim 12h-23h',
    rating: 4.5, lat: 48.8517, lng: 2.3388 },
  { id: 'mock-r2', name: 'Marché des Enfants Rouges', category: 'restaurant',
    address: '39 Rue de Bretagne, 75003 Paris', distance: '0.9 km',
    description: 'Le plus vieux marché couvert de Paris (1628), street food du monde entier sous les halles.',
    openingHours: 'Mar-Sam 8h30-20h30',
    rating: 4.4, lat: 48.8625, lng: 2.3594 },
  { id: 'mock-r3', name: 'Café de Flore', category: 'restaurant',
    address: '172 Bd Saint-Germain, 75006', distance: '2.2 km',
    description: 'Café mythique de Saint-Germain-des-Prés, temple des existentialistes et gens de lettres.',
    openingHours: 'Lun-Dim 7h30-1h30',
    rating: 4.3, lat: 48.8539, lng: 2.3327 },
  { id: 'mock-r4', name: 'Brasserie Lipp', category: 'restaurant',
    address: '151 Bd Saint-Germain, 75006', distance: '2.0 km',
    description: 'Brasserie historique depuis 1880, choucroute garnie et atmosphère parisienne immuable.',
    openingHours: 'Lun-Dim 11h-1h',
    rating: 4.2, lat: 48.8540, lng: 2.3344 },
  { id: 'mock-r5', name: 'Frenchie Bar à Vins', category: 'restaurant',
    address: '6 Rue du Nil, 75002 Paris', distance: '1.4 km',
    description: 'Cuisine bistronomique créative, produits de saison et vins naturels dans la rue du Nil.',
    openingHours: 'Lun-Sam 19h-0h',
    rating: 4.6, lat: 48.8642, lng: 2.3480 },

  // ── Nature ───────────────────────────────────────────────────────
  { id: 'mock-n1', name: 'Jardin du Luxembourg', category: 'nature',
    address: 'Rue de Médicis, 75006 Paris', distance: '1.5 km',
    description: 'Magnifique jardin à la française avec fontaines, statues, ruches et parterres fleuris.',
    openingHours: 'Ouvert tous les jours (horaires saisonniers)',
    rating: 4.8, lat: 48.8462, lng: 2.3372 },
  { id: 'mock-n2', name: 'Coulée Verte René-Dumont', category: 'nature',
    address: 'Avenue Daumesnil, 75012 Paris', distance: '3.2 km',
    description: 'Promenade suspendue sur les anciennes voies ferrées de la Bastille, 4.5 km de jardins.',
    openingHours: 'Lun-Ven 8h-21h, Sam-Dim 9h-21h',
    rating: 4.6, lat: 48.8526, lng: 2.3762 },
  { id: 'mock-n3', name: 'Parc des Buttes-Chaumont', category: 'nature',
    address: 'Rue Botzaris, 75019 Paris', distance: '4.1 km',
    description: 'Parc romantique avec îlot rocheux, temple de la Sibylle et lac pittoresque.',
    openingHours: 'Ouvert tous les jours 7h-21h',
    rating: 4.7, lat: 48.8795, lng: 2.3819 },
  { id: 'mock-n4', name: 'Berges de la Seine', category: 'nature',
    address: 'Voie Georges Pompidou, 75004', distance: '0.6 km',
    description: 'Promenade piétonne et végétalisée le long de la Seine, activités sportives et détente.',
    openingHours: 'Ouvert 24h/24',
    rating: 4.5, lat: 48.8568, lng: 2.3477 },
  { id: 'mock-n5', name: 'Bois de Vincennes', category: 'nature',
    address: 'Avenue de Saint-Maurice, 75012', distance: '4.9 km',
    description: 'Le plus grand espace vert de Paris : château, lac, hippodrome, zoo et jardins tropicaux.',
    openingHours: 'Ouvert 24h/24',
    rating: 4.6, lat: 48.8365, lng: 2.4321 },

  // ── Spectacles ───────────────────────────────────────────────────
  { id: 'mock-s1', name: 'Opéra Bastille', category: 'show',
    address: 'Place de la Bastille, 75012', distance: '2.4 km',
    description: "Opéra National de Paris, programmation lyrique et chorégraphique de renommée mondiale.",
    openingHours: 'Billetterie Lun-Sam 11h-18h30', website: 'https://www.operadeparis.fr',
    rating: 4.6, lat: 48.8531, lng: 2.3694 },
  { id: 'mock-s2', name: 'Comédie-Française', category: 'show',
    address: 'Place Colette, 75001 Paris', distance: '1.1 km',
    description: 'La Maison de Molière, fondée en 1680 — répertoire classique et contemporain.',
    openingHours: 'Billetterie Lun-Dim 11h-18h', website: 'https://www.comedie-francaise.fr',
    rating: 4.5, lat: 48.8631, lng: 2.3366 },
  { id: 'mock-s3', name: 'Le Grand Rex', category: 'show',
    address: '1 Bd Poissonnière, 75002 Paris', distance: '1.7 km',
    description: "Plus grande salle de cinéma d'Europe (2800 places), Art Déco somptueux.",
    openingHours: 'Ouvert tous les jours selon programmation',
    rating: 4.4, lat: 48.8700, lng: 2.3497 },
  { id: 'mock-s4', name: 'Philharmonie de Paris', category: 'show',
    address: '221 Avenue Jean Jaurès, 75019', distance: '4.9 km',
    description: 'Salle de concert de renommée mondiale (2400 places), acoustique parfaite.',
    website: 'https://philharmoniedeparis.fr', openingHours: 'Selon programmation',
    rating: 4.7, lat: 48.8894, lng: 2.3934 },
  { id: 'mock-s5', name: 'Théâtre du Châtelet', category: 'show',
    address: '2 Rue Edouard Colonne, 75001', distance: '1.0 km',
    description: 'Grande salle parisienne : opéras, comédies musicales, concerts événementiels.',
    openingHours: 'Billetterie Mar-Sam 11h-19h',
    rating: 4.5, lat: 48.8594, lng: 2.3484 },

  // ── Loisirs ───────────────────────────────────────────────────────
  { id: 'mock-a1', name: "Jardin d'Acclimatation", category: 'amusement',
    address: 'Bois de Boulogne, 75116 Paris', distance: '4.6 km',
    description: "Parc d'attractions familial avec manèges, ateliers créatifs, animaux et spectacles.",
    openingHours: 'Lun-Ven 11h-19h, Sam-Dim 10h-20h', website: 'https://www.jardindacclimatation.fr',
    rating: 4.3, lat: 48.8762, lng: 2.2549 },
  { id: 'mock-a2', name: 'Escape Hunt Paris', category: 'amusement',
    address: '11 Rue Saint-Marc, 75002 Paris', distance: '1.5 km',
    description: 'Escape games immersifs de 60 minutes : énigmes, indices cachés, ambiances uniques.',
    openingHours: 'Lun-Dim 10h-23h',
    rating: 4.5, lat: 48.8692, lng: 2.3435 },
  { id: 'mock-a3', name: 'Bowling de Paris', category: 'amusement',
    address: "Jardin d'Acclimatation, 75116", distance: '4.7 km',
    description: "24 pistes de bowling, billard américain, jeux d'arcade et ambiance festive.",
    openingHours: 'Lun-Dim 10h-2h',
    rating: 3.8, lat: 48.8758, lng: 2.2571 },
  { id: 'mock-a4', name: 'Aquaboulevard de Paris', category: 'amusement',
    address: '4 Rue Louis Armand, 75015', distance: '4.2 km',
    description: 'Plus grand parc aquatique de France en intérieur : toboggans, vagues, espace tropical.',
    openingHours: 'Lun-Jeu 9h-23h, Ven-Dim 8h-0h', website: 'https://www.aquaboulevard.fr',
    rating: 4.1, lat: 48.8336, lng: 2.2783 },
  { id: 'mock-a5', name: 'Laser Game Évolution', category: 'amusement',
    address: '78 Rue du Fg du Temple, 75011', distance: '2.1 km',
    description: "Arènes de laser game sur 600 m², scénarios variés, idéal pour groupes et anniversaires.",
    openingHours: 'Lun-Dim 13h-0h',
    rating: 4.3, lat: 48.8663, lng: 2.3681 },
]
